on: push
name: Deploy
jobs:
  onlyMaster:
    name: OnlyMaster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: OnlyMaster
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run build:github
        FOLDER: docs
